app01/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# @Time     :   2019/5/13 7:45
# @Author   :   robert
# @FileName :   urls.py
# @Software :   PyCharm

from django.urls import path,re_path
from app01.tests import *
from app01.views import *
app_name = 'app01'
urlpatterns = [
    path('login', login),
    # 作者对应关系
    path('user_list', user_list,name='user'),
    path('add_user', add_user),
    path('del_user', del_user),
    path('change_user', change_user),
    # 书籍对应关系
    path('add_book', add_book),
    path('book_list', book_list,name='book'),
    path('edit_book', edit_book),
    path('del_book', del_book),
    # 出版社对应关系
    path('publisher_list', publisher_list,name='publisher'),
    # path('add_publisher',add_publisher),
    path('add_publisher', AddPublisher.as_view()),
    path('del_publisher', del_publisher),
    path('edit_publisher', edit_publisher),
    re_path(r't_test/(?P<a>[0-9]+)/(?P<c>[0-9]+)/(?P<b>[0-9]+)/',yimi,name='test'),
    path('upload_file', upload_file),
    path('index',index),
    path('t_test2',t_test2),
    path('test',test),
    re_path('yimi/(?P<a>[0-9]+)/(?P<b>[0-9]+)/(?P<c>[0-9]+)',yimi,name='yimi'),
]

full_stack/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from app01.views import *
import app01.urls
import app03.urls
import session_app.urls
import wenjie.urls
import ajax_demo.urls

urlpatterns = [
    re_path(r'^wenjie/',include(wenjie.urls)),
    path('admin/', admin.site.urls),
    re_path(r'^app01/',include(app01.urls)),
    re_path(r'^app03/',include(app03.urls)),
    re_path(r'^session_app/',include(session_app.urls)),
    re_path(r'^ajax_demo/',include(ajax_demo.urls)),
]

wenjie/urls.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# @Time     :   2019/5/13 10:40
# @Author   :   robert
# @FileName :   urls.py
# @Software :   PyCharm

from django.urls import path,re_path

from wenjie.views import *

app_name = 'wenjie'
urlpatterns = [
    path('test1',test1,name='test'),
    path('create_person',create_person),
    path('change_person',change_person),
]

app01/models.py
from django.db import models

# Create your models here.

# 作者
class Author(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(null=False,max_length=20)
    book = models.ManyToManyField(to='Book')
    detail = models.OneToOneField(to='AuthorDetail',on_delete=models.CASCADE,default=None,null=True)
    def __str__(self):
        return "<{}-{}>".format(self.id,self.name)

# 作者详情
class AuthorDetail(models.Model):
    id = models.AutoField(primary_key=True)
    hobby = models.CharField(max_length=32)
    phone = models.IntegerField()
    addr = models.CharField(max_length=128)

    def __str__(self):
        return f'{self.id}=={self.addr}'


class Book(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64,null=False)
    price = models.DecimalField(max_digits=6,decimal_places=2,null=True,default=99.99)
    inventory = models.IntegerField(default=9999)
    quantity_sold = models.PositiveIntegerField(default=0)
    publisher = models.ForeignKey(to="Publisher",on_delete=models.SET_NULL,blank=True,null=True,default=1,related_name='books')

    def __str__(self):
        return "<{}-{}-{}>".format(self.id,self.title,self.publisher)

class Publisher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=40,null=False,unique=True)
    addr = models.CharField(max_length=200,null=True,default=None)

    def __str__(self):
        return "<{}-{}>".format(self.name,self.addr)

templates/1.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/bootstrap/css/bootstrap.min.css">
</head>
<body>
<nav>
  <ul class="pager">
    <li class="previous"><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
    <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
  </ul>
</nav>
<script src="/static/jquery-3.3.0.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/author.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>序号</th>
                <th>id</th>
                <th>作者名称</th>
            </tr>
            </thead>
            <tbody>
            {% for author in authors %}

            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ author.id }}</td>
                <td>{{ author.name }}</td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="row">
        <nav>
            <ul class="pagination">
                {{ page_html|safe }}
            </ul>
        </nav>
    </div>
</div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link rel="icon" href="/static/img/favicon.ico">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
{#    <link rel="stylesheet" href="{%  static 'bootstrap/css/bootstrap.min.css' %} ">#}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css">
    <style>
        body {
            padding: 70px;
        }
    </style>
</head>
<body>

<div class="container">
    {# 导航栏开始 #}
    <div class="row">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand">Robert</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#"></button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">首页</a></li>
                        <li class="{% block book_active %} {% endblock %}"><a href="publisher_list">读书馆</a></li>
                        <li class="{% block publisher_active %} {% endblock %}"><a href="{% url 'publisher' %}">出版社</a></li>
                        <li class="{% block user_active %} {% endblock %}"><a href="{% url 'user' %}">作者</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {# 导航栏结束 #}
{% block body %}
{% endblock %}
</div>
<script src="/static/jquery-3.3.0.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
{% block javascript %}
{% endblock %}

</body>
</html>

templates/book_list.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>书籍列表</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link rel="icon" href="/static/img/favicon.ico">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <style>
        body {
            padding: 70px;
        }
    </style>
</head>
<body>
<div class="container">
    {# 导航栏开始 #}
    <div class="row">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand">Robert</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#"></button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">首页</a></li>
                        <li class="active"><a href="/book_list">读书馆</a></li>
                        <li><a href="/publisher_list">出版社</a></li>
                        <li><a href="/user_list">作者</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {# 导航栏结束 #}
    {# 书籍列表开始 #}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3   panel panel-primary">
            <div class="panel-heading">
                <h4>书籍列表</h4>
            </div>
            <div class="panel-body table-responsive">
                <button type="button" class="btn btn-primary pull-right btn-xs add" data-toggle="modal"
                        data-target="#myModal">
                    新增
                </button>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>书名</th>
                        <th>出版社</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in all_books %}
                        <tr>
                            <td>{{ book.id }}</td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.publisher.name }}</td>
                            <td>
                                {% for author in book.author_set.all %}

                                    {% if loop.last %}
                                        {{ author.name }}
                                    {% else %}
                                        {{ author.name }} |
                                    {% endif %}
                                {% endfor %}

                            </td>
                            <td><a href="/edit_book?id={{ book.id }}" class="btn btn-success btn-xs">编辑</a>
                                <a href="/del_book?id={{ book.id }}" class="btn btn-danger btn-xs">删除</a></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>


        </div>
    </div>
    {# 书籍列表结束 #}
    {# modal开始 #}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新增书籍</h4>
                </div>
                <div class="modal-body row">
                    <form action="/add_book" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label for="title" class="col-sm-3 control-label">书名</label>
                            <div class="col-sm-6">
                                <input type="text" id="title" class="form-control" name="title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="publisher" class="col-sm-3 control-label">出版社</label>
                            <div class="col-sm-6">
                                {#                                <input type="text" id="publisher" class="form-control" name="publisher">#}
                                <select name="publisher_id" class="form-control">
                                    {% for publisher in publishers %}
                                        <option value="{{ publisher.id }}">{{ publisher.name }}</option>
                                    {% endfor %}

                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
    {# modal结束 #}
</div>
<script src="/static/jquery-3.3.0.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    $('button.add').on('click', function () {
        $('input#title').val('');
    })
</script>
</body>
</html>

templates/books.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    {% load static %}
    {% load app03_filters %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>id</th>
                    <th>书名</th>
                </tr>
            </thead>
            <tbody>
            {% for book in books %}
                            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
            </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>
    <div class="row">
        <nav>
            <ul class="pagination">
                {{ pager_html|safe }}
            </ul>
        </nav>
    </div>
</div>

<script src="{{ STATIC_PREFIX }}jquery-3.3.0.min.js"></script>
<script src="{{ STATIC_PREFIX }}bootstrap/js/bootstrap.min.js"></script>
<script>
    var page = window.location.href.split('/').slice(-1)[0];
    console.log(page);
    $('a[href="'+page+'"]').parent().addClass('active');

</script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <style>
        body {
            padding: 70px;
        }
    </style>
</head>
<body>
<div class="container">
{# 导航栏开始 #}
         <div class="row">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a href="#" class="navbar-brand">Robert</a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#"></button>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="/">首页</a></li>
                            <li ><a href="/book_list">读书馆</a></li>
                            <li><a href="/publisher_list">出版社</a></li>
                            <li  ><a href="/user_list">作者</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
{# 导航栏结束 #}
</div>

<script src="/static/jquery-3.3.0.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <style>
        .c1 {
            margin-top: 150px;

        }

        body {
            background-color: #eeeeee;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row c1">
        <div class="col-sm-4 col-sm-offset-4">

            <form action="/login" method="post" class="form-horizontal">
                <div style="margin-bottom: 10px" class="col-sm-offset-3 col-sm-9"><h3 class="text-center">欢迎登陆</h3>
                </div>

                <div class="form-group">
                    <label for="userName" class="col-sm-3 control-label">
                    </label>
                    <div class="col-sm-9 input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <input id="userName" name="userName" class="form-control" type="text">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-3 control-label">
                    </label>
                    <div class="col-sm-9 input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input id="password" name="password" class="form-control" type="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <label class="control-label">
                            记住密码 <input type="checkbox">
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <input type="submit" class="btn btn-primary btn-block" value="登陆">

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <div class="text-center text-danger">
                            {{ error_message }}
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-4 col-xs-4"></div>
    </div>
</div>

<script src="/static/jquery-3.3.0.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/login_app03.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css ">
</head>
</head>
<body>

<div class="container">
    <div class="row">
        <form action="login" method="post" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-3 control-label">账号:</label>
                <div class="col-sm-5">
                    <input type="text" id="userame" class="form-control" name="username" placeholder="请输入账号">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-3 control-label">密码:</label>
                <div class="col-sm-5">
                    <input type="text" id="password" class="form-control" name="password" placeholder="请输入密码">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-5 col-sm-offset-3">
                    <button type="submit" class="btn btn-success pull-right">提交</button>
                </div>
            </div>
        </form>
    </div>
</div>

</body>
</html>

templates/new_book_list.html
{% extends 'base.html' %}

{% block title %} 书籍{% endblock %}

{% block book_active %}
active
{% endblock %}


{% block body %}

    {# 书籍列表开始 #}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3   panel panel-primary">
            <div class="panel-heading">
                <h4>书籍列表</h4>
            </div>
            <div class="panel-body table-responsive">
                <button type="button" class="btn btn-primary pull-right btn-xs add" data-toggle="modal"
                        data-target="#myModal">
                    新增
                </button>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>序号</th>
                        <th>书名</th>
                        <th>出版社</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in all_books %}
                        <tr>
                            <td>{{ book.id }}</td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.publisher.name }}</td>
                            <td>
                                {% for author in book.author_set.all %}

                                    {% if loop.last %}
                                        {{ author.name }}
                                    {% else %}
                                        {{ author.name }} |
                                    {% endif %}
                                {% endfor %}

                            </td>
                            <td><a href="/edit_book?id={{ book.id }}" class="btn btn-success btn-xs">编辑</a>
                                <a href="/del_book?id={{ book.id }}" class="btn btn-danger btn-xs">删除</a></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>


        </div>
    </div>
    {# 书籍列表结束 #}
    {# modal开始 #}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新增书籍</h4>
                </div>
                <div class="modal-body row">
                    <form action="/add_book" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label for="title" class="col-sm-3 control-label">书名</label>
                            <div class="col-sm-6">
                                <input type="text" id="title" class="form-control" name="title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="publisher" class="col-sm-3 control-label">出版社</label>
                            <div class="col-sm-6">
                                {#                                <input type="text" id="publisher" class="form-control" name="publisher">#}
                                <select name="publisher_id" class="form-control">
                                    {% for publisher in publishers %}
                                        <option value="{{ publisher.id }}">{{ publisher.name }}</option>
                                    {% endfor %}

                                </select>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
    {# modal结束 #}
{% endblock %}

{% block javascript %}

    <script>
        $('button.add').on('click', function () {
            $('input#title').val('');
        })
    </script>
{% endblock %}

templates/new_publisher_list.html
{% extends 'base.html' %}

{% block title %} 出版社{% endblock %}

{% block publisher_active %}
active
{% endblock %}

{% block body %}
    <div class="row">


        <div class="col-sm-8 col-sm-offset-2 table-responsive">
            <div class="page-header">
                <h4>出版社
                    <small>信息展示</small>
                </h4>
            </div>

            <div>
                <button type="button" class="btn btn-success pull-right" data-toggle="modal"
                        data-target="#publisherModal">新增
                </button>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>序号</th>
                    <th>出版社名称</th>
                    <th>出版社地址</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for publisher in publishers %}
                    <tr>
                        <td>{{ publisher.id }}</td>
                        <td>{{ publisher.name }}</td>
                        <td>{{ publisher.addr }}</td>
                        <td><a href="/del_publisher?id={{ publisher.id }}" class="btn btn-danger">删除</a>
                            <button class="btn btn-default edit_publisher" data-toggle="modal" data-target="#editModal">
                                编辑
                            </button>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="modal fade" id="publisherModal" tabindex="-1" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">新增出版社</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <form action="/add_publisher" method="post" class="form form-horizontal">
                                <div class="form-group">
                                    <label for="" class="col-sm-3 control-label">出版社名称</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="publisher_name" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" class="col-sm-3 control-label">地址</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="publisher_addr" class="form-control">
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                    <button type="submit" class="btn btn-primary">保存</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>


            </div>

        </div>
        <div class="modal fade" id="editModal" tabindex="-1" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">编辑出版社</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <form action="/edit_publisher" method="post" class="form form-horizontal">
                                <input type="text" class="hidden" name="publisher_id" id="publisher_id">
                                <div class="form-group">
                                    <label for="" class="col-sm-3 control-label">出版社名称</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="publisher_name" id="publisher_name"
                                               class="form-control">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" class="col-sm-3 control-label">地址</label>
                                    <div class="col-sm-6">
                                        <input type="text" name="publisher_addr" id="publisher_addr"
                                               class="form-control">
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                    <button type="submit" class="btn btn-primary">保存</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>


            </div>

        </div>
    </div>
{% endblock %}


{% block javascript %}

    <script src="/static/js/publisher_list.js"></script>
{% endblock %}

templates/transfer.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    <div class="row">
        金额:<input type="text">
    </div>
</div>

</body>
</html>

templates/yimi.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,
maximum-scale=1, user-scalable=no">
    <link href="https://cdn.bootcss.com/normalize/8.0.1/normalize.min.css" rel="stylesheet">

</head>
<body>

{% load static %}
<a href="{% url 'wenjie:test' %}">点我</a>
</body>
</html>